// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package layerdb

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	go_digest "github.com/opencontainers/go-digest"
	_v1 "github.com/opencontainers/image-spec/specs-go/v1"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4f09cf66DecodeGithubComModelCiApackPkgLayerdb(in *jlexer.Lexer, out *OCILayout) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "mediaType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MediaType = string(in.String())
			}
		case "imageLayoutVersion":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4f09cf66EncodeGithubComModelCiApackPkgLayerdb(out *jwriter.Writer, in OCILayout) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"mediaType\":"
		out.RawString(prefix[1:])
		out.String(string(in.MediaType))
	}
	{
		const prefix string = ",\"imageLayoutVersion\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OCILayout) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4f09cf66EncodeGithubComModelCiApackPkgLayerdb(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OCILayout) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4f09cf66EncodeGithubComModelCiApackPkgLayerdb(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OCILayout) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4f09cf66DecodeGithubComModelCiApackPkgLayerdb(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OCILayout) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4f09cf66DecodeGithubComModelCiApackPkgLayerdb(l, v)
}
func easyjson4f09cf66DecodeGithubComModelCiApackPkgLayerdb1(in *jlexer.Lexer, out *Manifest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "mediaType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MediaType = string(in.String())
			}
		case "artifactType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ArtifactType = string(in.String())
			}
		case "config":
			easyjson4f09cf66DecodeGithubComOpencontainersImageSpecSpecsGoV1(in, &out.Config)
		case "layers":
			if in.IsNull() {
				in.Skip()
				out.Layers = nil
			} else {
				in.Delim('[')
				if out.Layers == nil {
					if !in.IsDelim(']') {
						out.Layers = make([]_v1.Descriptor, 0, 0)
					} else {
						out.Layers = []_v1.Descriptor{}
					}
				} else {
					out.Layers = (out.Layers)[:0]
				}
				for !in.IsDelim(']') {
					var v1 _v1.Descriptor
					easyjson4f09cf66DecodeGithubComOpencontainersImageSpecSpecsGoV1(in, &v1)
					out.Layers = append(out.Layers, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "subject":
			if in.IsNull() {
				in.Skip()
				out.Subject = nil
			} else {
				if out.Subject == nil {
					out.Subject = new(_v1.Descriptor)
				}
				easyjson4f09cf66DecodeGithubComOpencontainersImageSpecSpecsGoV1(in, out.Subject)
			}
		case "annotations":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Annotations = make(map[string]string)
				} else {
					out.Annotations = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v2 string
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = string(in.String())
					}
					(out.Annotations)[key] = v2
					in.WantComma()
				}
				in.Delim('}')
			}
		case "schemaVersion":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SchemaVersion = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4f09cf66EncodeGithubComModelCiApackPkgLayerdb1(out *jwriter.Writer, in Manifest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.MediaType != "" {
		const prefix string = ",\"mediaType\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.MediaType))
	}
	if in.ArtifactType != "" {
		const prefix string = ",\"artifactType\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ArtifactType))
	}
	{
		const prefix string = ",\"config\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson4f09cf66EncodeGithubComOpencontainersImageSpecSpecsGoV1(out, in.Config)
	}
	{
		const prefix string = ",\"layers\":"
		out.RawString(prefix)
		if in.Layers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Layers {
				if v3 > 0 {
					out.RawByte(',')
				}
				easyjson4f09cf66EncodeGithubComOpencontainersImageSpecSpecsGoV1(out, v4)
			}
			out.RawByte(']')
		}
	}
	if in.Subject != nil {
		const prefix string = ",\"subject\":"
		out.RawString(prefix)
		easyjson4f09cf66EncodeGithubComOpencontainersImageSpecSpecsGoV1(out, *in.Subject)
	}
	if len(in.Annotations) != 0 {
		const prefix string = ",\"annotations\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v5First := true
			for v5Name, v5Value := range in.Annotations {
				if v5First {
					v5First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v5Name))
				out.RawByte(':')
				out.String(string(v5Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"schemaVersion\":"
		out.RawString(prefix)
		out.Int(int(in.SchemaVersion))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Manifest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4f09cf66EncodeGithubComModelCiApackPkgLayerdb1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Manifest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4f09cf66EncodeGithubComModelCiApackPkgLayerdb1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Manifest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4f09cf66DecodeGithubComModelCiApackPkgLayerdb1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Manifest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4f09cf66DecodeGithubComModelCiApackPkgLayerdb1(l, v)
}
func easyjson4f09cf66DecodeGithubComOpencontainersImageSpecSpecsGoV1(in *jlexer.Lexer, out *_v1.Descriptor) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "mediaType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MediaType = string(in.String())
			}
		case "digest":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Digest = go_digest.Digest(in.String())
			}
		case "size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Size = int64(in.Int64())
			}
		case "urls":
			if in.IsNull() {
				in.Skip()
				out.URLs = nil
			} else {
				in.Delim('[')
				if out.URLs == nil {
					if !in.IsDelim(']') {
						out.URLs = make([]string, 0, 4)
					} else {
						out.URLs = []string{}
					}
				} else {
					out.URLs = (out.URLs)[:0]
				}
				for !in.IsDelim(']') {
					var v6 string
					if in.IsNull() {
						in.Skip()
					} else {
						v6 = string(in.String())
					}
					out.URLs = append(out.URLs, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "annotations":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Annotations = make(map[string]string)
				} else {
					out.Annotations = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v7 string
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = string(in.String())
					}
					(out.Annotations)[key] = v7
					in.WantComma()
				}
				in.Delim('}')
			}
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				out.Data = in.Bytes()
			}
		case "platform":
			if in.IsNull() {
				in.Skip()
				out.Platform = nil
			} else {
				if out.Platform == nil {
					out.Platform = new(_v1.Platform)
				}
				easyjson4f09cf66DecodeGithubComOpencontainersImageSpecSpecsGoV11(in, out.Platform)
			}
		case "artifactType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ArtifactType = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4f09cf66EncodeGithubComOpencontainersImageSpecSpecsGoV1(out *jwriter.Writer, in _v1.Descriptor) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"mediaType\":"
		out.RawString(prefix[1:])
		out.String(string(in.MediaType))
	}
	{
		const prefix string = ",\"digest\":"
		out.RawString(prefix)
		out.String(string(in.Digest))
	}
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.Int64(int64(in.Size))
	}
	if len(in.URLs) != 0 {
		const prefix string = ",\"urls\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v9, v10 := range in.URLs {
				if v9 > 0 {
					out.RawByte(',')
				}
				out.String(string(v10))
			}
			out.RawByte(']')
		}
	}
	if len(in.Annotations) != 0 {
		const prefix string = ",\"annotations\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v11First := true
			for v11Name, v11Value := range in.Annotations {
				if v11First {
					v11First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v11Name))
				out.RawByte(':')
				out.String(string(v11Value))
			}
			out.RawByte('}')
		}
	}
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Data)
	}
	if in.Platform != nil {
		const prefix string = ",\"platform\":"
		out.RawString(prefix)
		easyjson4f09cf66EncodeGithubComOpencontainersImageSpecSpecsGoV11(out, *in.Platform)
	}
	if in.ArtifactType != "" {
		const prefix string = ",\"artifactType\":"
		out.RawString(prefix)
		out.String(string(in.ArtifactType))
	}
	out.RawByte('}')
}
func easyjson4f09cf66DecodeGithubComOpencontainersImageSpecSpecsGoV11(in *jlexer.Lexer, out *_v1.Platform) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "architecture":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Architecture = string(in.String())
			}
		case "os":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OS = string(in.String())
			}
		case "os.version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OSVersion = string(in.String())
			}
		case "os.features":
			if in.IsNull() {
				in.Skip()
				out.OSFeatures = nil
			} else {
				in.Delim('[')
				if out.OSFeatures == nil {
					if !in.IsDelim(']') {
						out.OSFeatures = make([]string, 0, 4)
					} else {
						out.OSFeatures = []string{}
					}
				} else {
					out.OSFeatures = (out.OSFeatures)[:0]
				}
				for !in.IsDelim(']') {
					var v14 string
					if in.IsNull() {
						in.Skip()
					} else {
						v14 = string(in.String())
					}
					out.OSFeatures = append(out.OSFeatures, v14)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "variant":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Variant = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4f09cf66EncodeGithubComOpencontainersImageSpecSpecsGoV11(out *jwriter.Writer, in _v1.Platform) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"architecture\":"
		out.RawString(prefix[1:])
		out.String(string(in.Architecture))
	}
	{
		const prefix string = ",\"os\":"
		out.RawString(prefix)
		out.String(string(in.OS))
	}
	if in.OSVersion != "" {
		const prefix string = ",\"os.version\":"
		out.RawString(prefix)
		out.String(string(in.OSVersion))
	}
	if len(in.OSFeatures) != 0 {
		const prefix string = ",\"os.features\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v15, v16 := range in.OSFeatures {
				if v15 > 0 {
					out.RawByte(',')
				}
				out.String(string(v16))
			}
			out.RawByte(']')
		}
	}
	if in.Variant != "" {
		const prefix string = ",\"variant\":"
		out.RawString(prefix)
		out.String(string(in.Variant))
	}
	out.RawByte('}')
}
func easyjson4f09cf66DecodeGithubComModelCiApackPkgLayerdb2(in *jlexer.Lexer, out *Index) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "mediaType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MediaType = string(in.String())
			}
		case "artifactType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ArtifactType = string(in.String())
			}
		case "manifests":
			if in.IsNull() {
				in.Skip()
				out.Manifests = nil
			} else {
				in.Delim('[')
				if out.Manifests == nil {
					if !in.IsDelim(']') {
						out.Manifests = make([]_v1.Descriptor, 0, 0)
					} else {
						out.Manifests = []_v1.Descriptor{}
					}
				} else {
					out.Manifests = (out.Manifests)[:0]
				}
				for !in.IsDelim(']') {
					var v17 _v1.Descriptor
					easyjson4f09cf66DecodeGithubComOpencontainersImageSpecSpecsGoV1(in, &v17)
					out.Manifests = append(out.Manifests, v17)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "subject":
			if in.IsNull() {
				in.Skip()
				out.Subject = nil
			} else {
				if out.Subject == nil {
					out.Subject = new(_v1.Descriptor)
				}
				easyjson4f09cf66DecodeGithubComOpencontainersImageSpecSpecsGoV1(in, out.Subject)
			}
		case "annotations":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Annotations = make(map[string]string)
				} else {
					out.Annotations = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v18 string
					if in.IsNull() {
						in.Skip()
					} else {
						v18 = string(in.String())
					}
					(out.Annotations)[key] = v18
					in.WantComma()
				}
				in.Delim('}')
			}
		case "schemaVersion":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SchemaVersion = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4f09cf66EncodeGithubComModelCiApackPkgLayerdb2(out *jwriter.Writer, in Index) {
	out.RawByte('{')
	first := true
	_ = first
	if in.MediaType != "" {
		const prefix string = ",\"mediaType\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.MediaType))
	}
	if in.ArtifactType != "" {
		const prefix string = ",\"artifactType\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ArtifactType))
	}
	{
		const prefix string = ",\"manifests\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Manifests == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v19, v20 := range in.Manifests {
				if v19 > 0 {
					out.RawByte(',')
				}
				easyjson4f09cf66EncodeGithubComOpencontainersImageSpecSpecsGoV1(out, v20)
			}
			out.RawByte(']')
		}
	}
	if in.Subject != nil {
		const prefix string = ",\"subject\":"
		out.RawString(prefix)
		easyjson4f09cf66EncodeGithubComOpencontainersImageSpecSpecsGoV1(out, *in.Subject)
	}
	if len(in.Annotations) != 0 {
		const prefix string = ",\"annotations\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v21First := true
			for v21Name, v21Value := range in.Annotations {
				if v21First {
					v21First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v21Name))
				out.RawByte(':')
				out.String(string(v21Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"schemaVersion\":"
		out.RawString(prefix)
		out.Int(int(in.SchemaVersion))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Index) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4f09cf66EncodeGithubComModelCiApackPkgLayerdb2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Index) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4f09cf66EncodeGithubComModelCiApackPkgLayerdb2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Index) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4f09cf66DecodeGithubComModelCiApackPkgLayerdb2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Index) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4f09cf66DecodeGithubComModelCiApackPkgLayerdb2(l, v)
}
func easyjson4f09cf66DecodeGithubComModelCiApackPkgLayerdb3(in *jlexer.Lexer, out *Descriptor) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "mediaType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MediaType = string(in.String())
			}
		case "digest":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Digest = go_digest.Digest(in.String())
			}
		case "size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Size = int64(in.Int64())
			}
		case "urls":
			if in.IsNull() {
				in.Skip()
				out.URLs = nil
			} else {
				in.Delim('[')
				if out.URLs == nil {
					if !in.IsDelim(']') {
						out.URLs = make([]string, 0, 4)
					} else {
						out.URLs = []string{}
					}
				} else {
					out.URLs = (out.URLs)[:0]
				}
				for !in.IsDelim(']') {
					var v22 string
					if in.IsNull() {
						in.Skip()
					} else {
						v22 = string(in.String())
					}
					out.URLs = append(out.URLs, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "annotations":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Annotations = make(map[string]string)
				} else {
					out.Annotations = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v23 string
					if in.IsNull() {
						in.Skip()
					} else {
						v23 = string(in.String())
					}
					(out.Annotations)[key] = v23
					in.WantComma()
				}
				in.Delim('}')
			}
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				out.Data = in.Bytes()
			}
		case "platform":
			if in.IsNull() {
				in.Skip()
				out.Platform = nil
			} else {
				if out.Platform == nil {
					out.Platform = new(_v1.Platform)
				}
				easyjson4f09cf66DecodeGithubComOpencontainersImageSpecSpecsGoV11(in, out.Platform)
			}
		case "artifactType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ArtifactType = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4f09cf66EncodeGithubComModelCiApackPkgLayerdb3(out *jwriter.Writer, in Descriptor) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"mediaType\":"
		out.RawString(prefix[1:])
		out.String(string(in.MediaType))
	}
	{
		const prefix string = ",\"digest\":"
		out.RawString(prefix)
		out.String(string(in.Digest))
	}
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.Int64(int64(in.Size))
	}
	if len(in.URLs) != 0 {
		const prefix string = ",\"urls\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v25, v26 := range in.URLs {
				if v25 > 0 {
					out.RawByte(',')
				}
				out.String(string(v26))
			}
			out.RawByte(']')
		}
	}
	if len(in.Annotations) != 0 {
		const prefix string = ",\"annotations\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v27First := true
			for v27Name, v27Value := range in.Annotations {
				if v27First {
					v27First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v27Name))
				out.RawByte(':')
				out.String(string(v27Value))
			}
			out.RawByte('}')
		}
	}
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Data)
	}
	if in.Platform != nil {
		const prefix string = ",\"platform\":"
		out.RawString(prefix)
		easyjson4f09cf66EncodeGithubComOpencontainersImageSpecSpecsGoV11(out, *in.Platform)
	}
	if in.ArtifactType != "" {
		const prefix string = ",\"artifactType\":"
		out.RawString(prefix)
		out.String(string(in.ArtifactType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Descriptor) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4f09cf66EncodeGithubComModelCiApackPkgLayerdb3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Descriptor) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4f09cf66EncodeGithubComModelCiApackPkgLayerdb3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Descriptor) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4f09cf66DecodeGithubComModelCiApackPkgLayerdb3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Descriptor) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4f09cf66DecodeGithubComModelCiApackPkgLayerdb3(l, v)
}
func easyjson4f09cf66DecodeGithubComModelCiApackPkgLayerdb4(in *jlexer.Lexer, out *Config) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "created":
			if in.IsNull() {
				in.Skip()
				out.Created = nil
			} else {
				if out.Created == nil {
					out.Created = new(time.Time)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					if data := in.Raw(); in.Ok() {
						in.AddError((*out.Created).UnmarshalJSON(data))
					}
				}
			}
		case "author":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Author = string(in.String())
			}
		case "config":
			easyjson4f09cf66DecodeGithubComOpencontainersImageSpecSpecsGoV12(in, &out.Config)
		case "rootfs":
			easyjson4f09cf66DecodeGithubComOpencontainersImageSpecSpecsGoV13(in, &out.RootFS)
		case "history":
			if in.IsNull() {
				in.Skip()
				out.History = nil
			} else {
				in.Delim('[')
				if out.History == nil {
					if !in.IsDelim(']') {
						out.History = make([]_v1.History, 0, 1)
					} else {
						out.History = []_v1.History{}
					}
				} else {
					out.History = (out.History)[:0]
				}
				for !in.IsDelim(']') {
					var v30 _v1.History
					easyjson4f09cf66DecodeGithubComOpencontainersImageSpecSpecsGoV14(in, &v30)
					out.History = append(out.History, v30)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "architecture":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Architecture = string(in.String())
			}
		case "os":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OS = string(in.String())
			}
		case "os.version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OSVersion = string(in.String())
			}
		case "os.features":
			if in.IsNull() {
				in.Skip()
				out.OSFeatures = nil
			} else {
				in.Delim('[')
				if out.OSFeatures == nil {
					if !in.IsDelim(']') {
						out.OSFeatures = make([]string, 0, 4)
					} else {
						out.OSFeatures = []string{}
					}
				} else {
					out.OSFeatures = (out.OSFeatures)[:0]
				}
				for !in.IsDelim(']') {
					var v31 string
					if in.IsNull() {
						in.Skip()
					} else {
						v31 = string(in.String())
					}
					out.OSFeatures = append(out.OSFeatures, v31)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "variant":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Variant = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4f09cf66EncodeGithubComModelCiApackPkgLayerdb4(out *jwriter.Writer, in Config) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Created != nil {
		const prefix string = ",\"created\":"
		first = false
		out.RawString(prefix[1:])
		out.Raw((*in.Created).MarshalJSON())
	}
	if in.Author != "" {
		const prefix string = ",\"author\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Author))
	}
	if true {
		const prefix string = ",\"config\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson4f09cf66EncodeGithubComOpencontainersImageSpecSpecsGoV12(out, in.Config)
	}
	{
		const prefix string = ",\"rootfs\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson4f09cf66EncodeGithubComOpencontainersImageSpecSpecsGoV13(out, in.RootFS)
	}
	if len(in.History) != 0 {
		const prefix string = ",\"history\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v32, v33 := range in.History {
				if v32 > 0 {
					out.RawByte(',')
				}
				easyjson4f09cf66EncodeGithubComOpencontainersImageSpecSpecsGoV14(out, v33)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"architecture\":"
		out.RawString(prefix)
		out.String(string(in.Architecture))
	}
	{
		const prefix string = ",\"os\":"
		out.RawString(prefix)
		out.String(string(in.OS))
	}
	if in.OSVersion != "" {
		const prefix string = ",\"os.version\":"
		out.RawString(prefix)
		out.String(string(in.OSVersion))
	}
	if len(in.OSFeatures) != 0 {
		const prefix string = ",\"os.features\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v34, v35 := range in.OSFeatures {
				if v34 > 0 {
					out.RawByte(',')
				}
				out.String(string(v35))
			}
			out.RawByte(']')
		}
	}
	if in.Variant != "" {
		const prefix string = ",\"variant\":"
		out.RawString(prefix)
		out.String(string(in.Variant))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Config) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4f09cf66EncodeGithubComModelCiApackPkgLayerdb4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Config) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4f09cf66EncodeGithubComModelCiApackPkgLayerdb4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Config) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4f09cf66DecodeGithubComModelCiApackPkgLayerdb4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Config) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4f09cf66DecodeGithubComModelCiApackPkgLayerdb4(l, v)
}
func easyjson4f09cf66DecodeGithubComOpencontainersImageSpecSpecsGoV14(in *jlexer.Lexer, out *_v1.History) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "created":
			if in.IsNull() {
				in.Skip()
				out.Created = nil
			} else {
				if out.Created == nil {
					out.Created = new(time.Time)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					if data := in.Raw(); in.Ok() {
						in.AddError((*out.Created).UnmarshalJSON(data))
					}
				}
			}
		case "created_by":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedBy = string(in.String())
			}
		case "author":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Author = string(in.String())
			}
		case "comment":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Comment = string(in.String())
			}
		case "empty_layer":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EmptyLayer = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4f09cf66EncodeGithubComOpencontainersImageSpecSpecsGoV14(out *jwriter.Writer, in _v1.History) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Created != nil {
		const prefix string = ",\"created\":"
		first = false
		out.RawString(prefix[1:])
		out.Raw((*in.Created).MarshalJSON())
	}
	if in.CreatedBy != "" {
		const prefix string = ",\"created_by\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.CreatedBy))
	}
	if in.Author != "" {
		const prefix string = ",\"author\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Author))
	}
	if in.Comment != "" {
		const prefix string = ",\"comment\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Comment))
	}
	if in.EmptyLayer {
		const prefix string = ",\"empty_layer\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.EmptyLayer))
	}
	out.RawByte('}')
}
func easyjson4f09cf66DecodeGithubComOpencontainersImageSpecSpecsGoV13(in *jlexer.Lexer, out *_v1.RootFS) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "diff_ids":
			if in.IsNull() {
				in.Skip()
				out.DiffIDs = nil
			} else {
				in.Delim('[')
				if out.DiffIDs == nil {
					if !in.IsDelim(']') {
						out.DiffIDs = make([]go_digest.Digest, 0, 4)
					} else {
						out.DiffIDs = []go_digest.Digest{}
					}
				} else {
					out.DiffIDs = (out.DiffIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v36 go_digest.Digest
					if in.IsNull() {
						in.Skip()
					} else {
						v36 = go_digest.Digest(in.String())
					}
					out.DiffIDs = append(out.DiffIDs, v36)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4f09cf66EncodeGithubComOpencontainersImageSpecSpecsGoV13(out *jwriter.Writer, in _v1.RootFS) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"diff_ids\":"
		out.RawString(prefix)
		if in.DiffIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v37, v38 := range in.DiffIDs {
				if v37 > 0 {
					out.RawByte(',')
				}
				out.String(string(v38))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson4f09cf66DecodeGithubComOpencontainersImageSpecSpecsGoV12(in *jlexer.Lexer, out *_v1.ImageConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "User":
			if in.IsNull() {
				in.Skip()
			} else {
				out.User = string(in.String())
			}
		case "ExposedPorts":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.ExposedPorts = make(map[string]struct{})
				} else {
					out.ExposedPorts = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v39 struct{}
					easyjson4f09cf66Decode(in, &v39)
					(out.ExposedPorts)[key] = v39
					in.WantComma()
				}
				in.Delim('}')
			}
		case "Env":
			if in.IsNull() {
				in.Skip()
				out.Env = nil
			} else {
				in.Delim('[')
				if out.Env == nil {
					if !in.IsDelim(']') {
						out.Env = make([]string, 0, 4)
					} else {
						out.Env = []string{}
					}
				} else {
					out.Env = (out.Env)[:0]
				}
				for !in.IsDelim(']') {
					var v40 string
					if in.IsNull() {
						in.Skip()
					} else {
						v40 = string(in.String())
					}
					out.Env = append(out.Env, v40)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Entrypoint":
			if in.IsNull() {
				in.Skip()
				out.Entrypoint = nil
			} else {
				in.Delim('[')
				if out.Entrypoint == nil {
					if !in.IsDelim(']') {
						out.Entrypoint = make([]string, 0, 4)
					} else {
						out.Entrypoint = []string{}
					}
				} else {
					out.Entrypoint = (out.Entrypoint)[:0]
				}
				for !in.IsDelim(']') {
					var v41 string
					if in.IsNull() {
						in.Skip()
					} else {
						v41 = string(in.String())
					}
					out.Entrypoint = append(out.Entrypoint, v41)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Cmd":
			if in.IsNull() {
				in.Skip()
				out.Cmd = nil
			} else {
				in.Delim('[')
				if out.Cmd == nil {
					if !in.IsDelim(']') {
						out.Cmd = make([]string, 0, 4)
					} else {
						out.Cmd = []string{}
					}
				} else {
					out.Cmd = (out.Cmd)[:0]
				}
				for !in.IsDelim(']') {
					var v42 string
					if in.IsNull() {
						in.Skip()
					} else {
						v42 = string(in.String())
					}
					out.Cmd = append(out.Cmd, v42)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Volumes":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Volumes = make(map[string]struct{})
				} else {
					out.Volumes = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v43 struct{}
					easyjson4f09cf66Decode(in, &v43)
					(out.Volumes)[key] = v43
					in.WantComma()
				}
				in.Delim('}')
			}
		case "WorkingDir":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WorkingDir = string(in.String())
			}
		case "Labels":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Labels = make(map[string]string)
				} else {
					out.Labels = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v44 string
					if in.IsNull() {
						in.Skip()
					} else {
						v44 = string(in.String())
					}
					(out.Labels)[key] = v44
					in.WantComma()
				}
				in.Delim('}')
			}
		case "StopSignal":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StopSignal = string(in.String())
			}
		case "ArgsEscaped":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ArgsEscaped = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4f09cf66EncodeGithubComOpencontainersImageSpecSpecsGoV12(out *jwriter.Writer, in _v1.ImageConfig) {
	out.RawByte('{')
	first := true
	_ = first
	if in.User != "" {
		const prefix string = ",\"User\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.User))
	}
	if len(in.ExposedPorts) != 0 {
		const prefix string = ",\"ExposedPorts\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('{')
			v45First := true
			for v45Name, v45Value := range in.ExposedPorts {
				if v45First {
					v45First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v45Name))
				out.RawByte(':')
				easyjson4f09cf66Encode(out, v45Value)
			}
			out.RawByte('}')
		}
	}
	if len(in.Env) != 0 {
		const prefix string = ",\"Env\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v46, v47 := range in.Env {
				if v46 > 0 {
					out.RawByte(',')
				}
				out.String(string(v47))
			}
			out.RawByte(']')
		}
	}
	if len(in.Entrypoint) != 0 {
		const prefix string = ",\"Entrypoint\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v48, v49 := range in.Entrypoint {
				if v48 > 0 {
					out.RawByte(',')
				}
				out.String(string(v49))
			}
			out.RawByte(']')
		}
	}
	if len(in.Cmd) != 0 {
		const prefix string = ",\"Cmd\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v50, v51 := range in.Cmd {
				if v50 > 0 {
					out.RawByte(',')
				}
				out.String(string(v51))
			}
			out.RawByte(']')
		}
	}
	if len(in.Volumes) != 0 {
		const prefix string = ",\"Volumes\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('{')
			v52First := true
			for v52Name, v52Value := range in.Volumes {
				if v52First {
					v52First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v52Name))
				out.RawByte(':')
				easyjson4f09cf66Encode(out, v52Value)
			}
			out.RawByte('}')
		}
	}
	if in.WorkingDir != "" {
		const prefix string = ",\"WorkingDir\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.WorkingDir))
	}
	if len(in.Labels) != 0 {
		const prefix string = ",\"Labels\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('{')
			v53First := true
			for v53Name, v53Value := range in.Labels {
				if v53First {
					v53First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v53Name))
				out.RawByte(':')
				out.String(string(v53Value))
			}
			out.RawByte('}')
		}
	}
	if in.StopSignal != "" {
		const prefix string = ",\"StopSignal\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.StopSignal))
	}
	if in.ArgsEscaped {
		const prefix string = ",\"ArgsEscaped\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.ArgsEscaped))
	}
	out.RawByte('}')
}
func easyjson4f09cf66Decode(in *jlexer.Lexer, out *struct{}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4f09cf66Encode(out *jwriter.Writer, in struct{}) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}
