// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	spec "github.com/model-ci/apack/internal/spec"
	layerdb "github.com/model-ci/apack/pkg/layerdb"
	registry "oras.land/oras-go/v2/registry"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes(in *jlexer.Lexer, out *Response) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "task_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TaskID = string(in.String())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
				out.Message = nil
			} else {
				out.Message = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes(out *jwriter.Writer, in Response) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"task_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.TaskID))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Message)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Response) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Response) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Response) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Response) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes(l, v)
}
func easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes1(in *jlexer.Lexer, out *Request) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "ReferenceStr":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReferenceStr = string(in.String())
			}
		case "Reference":
			easyjson6601e8cdDecodeOrasLandOrasGoV2Registry(in, &out.Reference)
		case "Artifact":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Artifact).UnmarshalEasyJSON(in)
			}
		case "ConfigJSON":
			if in.IsNull() {
				in.Skip()
				out.ConfigJSON = nil
			} else {
				out.ConfigJSON = in.Bytes()
			}
		case "Overwrite":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Overwrite = bool(in.Bool())
			}
		case "Algo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Algo = layerdb.Algorithm(in.String())
			}
		case "Output":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Output = string(in.String())
			}
		case "TargetRef":
			easyjson6601e8cdDecodeOrasLandOrasGoV2Registry(in, &out.TargetRef)
		case "User":
			if in.IsNull() {
				in.Skip()
			} else {
				out.User = string(in.String())
			}
		case "Password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Password = string(in.String())
			}
		case "Tool":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Tool = string(in.String())
			}
		case "Endpoint":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Endpoint = string(in.String())
			}
		case "Repo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Repo = string(in.String())
			}
		case "Branch":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Branch = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes1(out *jwriter.Writer, in Request) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"ReferenceStr\":"
		out.RawString(prefix)
		out.String(string(in.ReferenceStr))
	}
	{
		const prefix string = ",\"Reference\":"
		out.RawString(prefix)
		easyjson6601e8cdEncodeOrasLandOrasGoV2Registry(out, in.Reference)
	}
	{
		const prefix string = ",\"Artifact\":"
		out.RawString(prefix)
		(in.Artifact).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"ConfigJSON\":"
		out.RawString(prefix)
		out.Base64Bytes(in.ConfigJSON)
	}
	{
		const prefix string = ",\"Overwrite\":"
		out.RawString(prefix)
		out.Bool(bool(in.Overwrite))
	}
	{
		const prefix string = ",\"Algo\":"
		out.RawString(prefix)
		out.String(string(in.Algo))
	}
	{
		const prefix string = ",\"Output\":"
		out.RawString(prefix)
		out.String(string(in.Output))
	}
	{
		const prefix string = ",\"TargetRef\":"
		out.RawString(prefix)
		easyjson6601e8cdEncodeOrasLandOrasGoV2Registry(out, in.TargetRef)
	}
	{
		const prefix string = ",\"User\":"
		out.RawString(prefix)
		out.String(string(in.User))
	}
	{
		const prefix string = ",\"Password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	{
		const prefix string = ",\"Tool\":"
		out.RawString(prefix)
		out.String(string(in.Tool))
	}
	{
		const prefix string = ",\"Endpoint\":"
		out.RawString(prefix)
		out.String(string(in.Endpoint))
	}
	{
		const prefix string = ",\"Repo\":"
		out.RawString(prefix)
		out.String(string(in.Repo))
	}
	{
		const prefix string = ",\"Branch\":"
		out.RawString(prefix)
		out.String(string(in.Branch))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Request) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Request) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Request) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Request) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes1(l, v)
}
func easyjson6601e8cdDecodeOrasLandOrasGoV2Registry(in *jlexer.Lexer, out *registry.Reference) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Registry":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Registry = string(in.String())
			}
		case "Repository":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Repository = string(in.String())
			}
		case "Reference":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reference = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeOrasLandOrasGoV2Registry(out *jwriter.Writer, in registry.Reference) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Registry\":"
		out.RawString(prefix[1:])
		out.String(string(in.Registry))
	}
	{
		const prefix string = ",\"Repository\":"
		out.RawString(prefix)
		out.String(string(in.Repository))
	}
	{
		const prefix string = ",\"Reference\":"
		out.RawString(prefix)
		out.String(string(in.Reference))
	}
	out.RawByte('}')
}
func easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes2(in *jlexer.Lexer, out *Logout) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Home":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Home = string(in.String())
			}
		case "Registry":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Registry = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes2(out *jwriter.Writer, in Logout) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Home\":"
		out.RawString(prefix[1:])
		out.String(string(in.Home))
	}
	{
		const prefix string = ",\"Registry\":"
		out.RawString(prefix)
		out.String(string(in.Registry))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Logout) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Logout) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Logout) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Logout) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes2(l, v)
}
func easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes3(in *jlexer.Lexer, out *Login) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "Password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Password = string(in.String())
			}
		case "Auth":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Auth).UnmarshalEasyJSON(in)
			}
		case "Home":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Home = string(in.String())
			}
		case "Registry":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Registry = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes3(out *jwriter.Writer, in Login) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Username\":"
		out.RawString(prefix[1:])
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"Password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	{
		const prefix string = ",\"Auth\":"
		out.RawString(prefix)
		(in.Auth).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"Home\":"
		out.RawString(prefix)
		out.String(string(in.Home))
	}
	{
		const prefix string = ",\"Registry\":"
		out.RawString(prefix)
		out.String(string(in.Registry))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Login) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Login) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Login) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Login) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes3(l, v)
}
func easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes4(in *jlexer.Lexer, out *Inspect) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Manifest":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Manifest).UnmarshalEasyJSON(in)
			}
		case "Config":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Config).UnmarshalEasyJSON(in)
			}
		case "Artifact":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Artifact).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes4(out *jwriter.Writer, in Inspect) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Manifest\":"
		out.RawString(prefix[1:])
		(in.Manifest).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"Config\":"
		out.RawString(prefix)
		(in.Config).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"Artifact\":"
		out.RawString(prefix)
		(in.Artifact).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Inspect) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Inspect) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Inspect) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Inspect) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes4(l, v)
}
func easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes5(in *jlexer.Lexer, out *HealthStatus) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes5(out *jwriter.Writer, in HealthStatus) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HealthStatus) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HealthStatus) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HealthStatus) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HealthStatus) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes5(l, v)
}
func easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes6(in *jlexer.Lexer, out *Description) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Action":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Action = string(in.String())
			}
		case "Reference":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reference = string(in.String())
			}
		case "Digest":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Digest = string(in.String())
			}
		case "Size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Size = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes6(out *jwriter.Writer, in Description) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Action\":"
		out.RawString(prefix[1:])
		out.String(string(in.Action))
	}
	{
		const prefix string = ",\"Reference\":"
		out.RawString(prefix)
		out.String(string(in.Reference))
	}
	{
		const prefix string = ",\"Digest\":"
		out.RawString(prefix)
		out.String(string(in.Digest))
	}
	{
		const prefix string = ",\"Size\":"
		out.RawString(prefix)
		out.String(string(in.Size))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Description) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Description) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Description) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Description) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes6(l, v)
}
func easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes7(in *jlexer.Lexer, out *Authentication) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "PlainHTTP":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PlainHTTP = bool(in.Bool())
			}
		case "TLSVerify":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TLSVerify = bool(in.Bool())
			}
		case "CredentialsPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CredentialsPath = string(in.String())
			}
		case "ClientCertPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClientCertPath = string(in.String())
			}
		case "ClientCertKeyPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ClientCertKeyPath = string(in.String())
			}
		case "Concurrency":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Concurrency = int(in.Int())
			}
		case "Proxy":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Proxy = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes7(out *jwriter.Writer, in Authentication) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"PlainHTTP\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.PlainHTTP))
	}
	{
		const prefix string = ",\"TLSVerify\":"
		out.RawString(prefix)
		out.Bool(bool(in.TLSVerify))
	}
	{
		const prefix string = ",\"CredentialsPath\":"
		out.RawString(prefix)
		out.String(string(in.CredentialsPath))
	}
	{
		const prefix string = ",\"ClientCertPath\":"
		out.RawString(prefix)
		out.String(string(in.ClientCertPath))
	}
	{
		const prefix string = ",\"ClientCertKeyPath\":"
		out.RawString(prefix)
		out.String(string(in.ClientCertKeyPath))
	}
	{
		const prefix string = ",\"Concurrency\":"
		out.RawString(prefix)
		out.Int(int(in.Concurrency))
	}
	{
		const prefix string = ",\"Proxy\":"
		out.RawString(prefix)
		out.String(string(in.Proxy))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Authentication) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Authentication) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Authentication) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Authentication) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes7(l, v)
}
func easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes8(in *jlexer.Lexer, out *Artifacts) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Count = int(in.Int())
			}
		case "Items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make([]spec.Artifact, 0, 0)
					} else {
						out.Items = []spec.Artifact{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v7 spec.Artifact
					if in.IsNull() {
						in.Skip()
					} else {
						(v7).UnmarshalEasyJSON(in)
					}
					out.Items = append(out.Items, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes8(out *jwriter.Writer, in Artifacts) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Count\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Count))
	}
	{
		const prefix string = ",\"Items\":"
		out.RawString(prefix)
		if in.Items == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Items {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Artifacts) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Artifacts) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Artifacts) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Artifacts) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes8(l, v)
}
func easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes9(in *jlexer.Lexer, out *Args) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Overwrite":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Overwrite = bool(in.Bool())
			}
		case "Algo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Algo = layerdb.Algorithm(in.String())
			}
		case "Output":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Output = string(in.String())
			}
		case "TargetRef":
			easyjson6601e8cdDecodeOrasLandOrasGoV2Registry(in, &out.TargetRef)
		case "User":
			if in.IsNull() {
				in.Skip()
			} else {
				out.User = string(in.String())
			}
		case "Password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Password = string(in.String())
			}
		case "Tool":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Tool = string(in.String())
			}
		case "Endpoint":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Endpoint = string(in.String())
			}
		case "Repo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Repo = string(in.String())
			}
		case "Branch":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Branch = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes9(out *jwriter.Writer, in Args) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Overwrite\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Overwrite))
	}
	{
		const prefix string = ",\"Algo\":"
		out.RawString(prefix)
		out.String(string(in.Algo))
	}
	{
		const prefix string = ",\"Output\":"
		out.RawString(prefix)
		out.String(string(in.Output))
	}
	{
		const prefix string = ",\"TargetRef\":"
		out.RawString(prefix)
		easyjson6601e8cdEncodeOrasLandOrasGoV2Registry(out, in.TargetRef)
	}
	{
		const prefix string = ",\"User\":"
		out.RawString(prefix)
		out.String(string(in.User))
	}
	{
		const prefix string = ",\"Password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	{
		const prefix string = ",\"Tool\":"
		out.RawString(prefix)
		out.String(string(in.Tool))
	}
	{
		const prefix string = ",\"Endpoint\":"
		out.RawString(prefix)
		out.String(string(in.Endpoint))
	}
	{
		const prefix string = ",\"Repo\":"
		out.RawString(prefix)
		out.String(string(in.Repo))
	}
	{
		const prefix string = ",\"Branch\":"
		out.RawString(prefix)
		out.String(string(in.Branch))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Args) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Args) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComModelCiApackInternalTypes9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Args) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Args) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComModelCiApackInternalTypes9(l, v)
}
