// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package options

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson24099d24DecodeGithubComModelCiApackInternalOptions(in *jlexer.Lexer, out *OptionConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "endpoint":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Endpoint = string(in.String())
			}
		case "auth":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Auth = bool(in.Bool())
			}
		case "username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Password = string(in.String())
			}
		case "cert":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cert = string(in.String())
			}
		case "key":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Key = string(in.String())
			}
		case "log":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Log = string(in.String())
			}
		case "log-level":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LogLevel = string(in.String())
			}
		case "root":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Root = string(in.String())
			}
		case "data-dir":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DataDir = string(in.String())
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "read-timeout":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReadTimeout = int(in.Int())
			}
		case "write-timeout":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WriteTimeout = int(in.Int())
			}
		case "idle-timeout":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IdleTimeout = int(in.Int())
			}
		case "tmp":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Tmp = string(in.String())
			}
		case "gc-percent":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GcPercent = int(in.Int())
			}
		case "memory-limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MemoryLimit = int(in.Int())
			}
		case "secure":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Secure = bool(in.Bool())
			}
		case "hosts":
			if in.IsNull() {
				in.Skip()
				out.Hosts = nil
			} else {
				in.Delim('[')
				if out.Hosts == nil {
					if !in.IsDelim(']') {
						out.Hosts = make([]string, 0, 4)
					} else {
						out.Hosts = []string{}
					}
				} else {
					out.Hosts = (out.Hosts)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.Hosts = append(out.Hosts, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "concurrency":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Concurrency = int(in.Int())
			}
		case "no-proxy":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NoProxy = bool(in.Bool())
			}
		case "compress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Compress = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson24099d24EncodeGithubComModelCiApackInternalOptions(out *jwriter.Writer, in OptionConfig) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Endpoint != "" {
		const prefix string = ",\"endpoint\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Endpoint))
	}
	if in.Auth {
		const prefix string = ",\"auth\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Auth))
	}
	if in.Username != "" {
		const prefix string = ",\"username\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Username))
	}
	if in.Password != "" {
		const prefix string = ",\"password\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Password))
	}
	if in.Cert != "" {
		const prefix string = ",\"cert\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Cert))
	}
	if in.Key != "" {
		const prefix string = ",\"key\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Key))
	}
	if in.Log != "" {
		const prefix string = ",\"log\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Log))
	}
	if in.LogLevel != "" {
		const prefix string = ",\"log-level\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.LogLevel))
	}
	if in.Root != "" {
		const prefix string = ",\"root\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Root))
	}
	if in.DataDir != "" {
		const prefix string = ",\"data-dir\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.DataDir))
	}
	if in.Body != "" {
		const prefix string = ",\"body\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Body))
	}
	if in.ReadTimeout != 0 {
		const prefix string = ",\"read-timeout\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ReadTimeout))
	}
	if in.WriteTimeout != 0 {
		const prefix string = ",\"write-timeout\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.WriteTimeout))
	}
	if in.IdleTimeout != 0 {
		const prefix string = ",\"idle-timeout\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.IdleTimeout))
	}
	if in.Tmp != "" {
		const prefix string = ",\"tmp\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Tmp))
	}
	if in.GcPercent != 0 {
		const prefix string = ",\"gc-percent\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.GcPercent))
	}
	if in.MemoryLimit != 0 {
		const prefix string = ",\"memory-limit\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.MemoryLimit))
	}
	if in.Secure {
		const prefix string = ",\"secure\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Secure))
	}
	if len(in.Hosts) != 0 {
		const prefix string = ",\"hosts\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v2, v3 := range in.Hosts {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	if in.Concurrency != 0 {
		const prefix string = ",\"concurrency\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Concurrency))
	}
	if in.NoProxy {
		const prefix string = ",\"no-proxy\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.NoProxy))
	}
	if in.Compress != 0 {
		const prefix string = ",\"compress\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Compress))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v OptionConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson24099d24EncodeGithubComModelCiApackInternalOptions(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v OptionConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson24099d24EncodeGithubComModelCiApackInternalOptions(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *OptionConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson24099d24DecodeGithubComModelCiApackInternalOptions(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *OptionConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson24099d24DecodeGithubComModelCiApackInternalOptions(l, v)
}
