// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package config

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6615c02eDecodeGithubComModelCiApackPkgLibllamaLlamafileConfig(in *jlexer.Lexer, out *RuntimeConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "server_config":
			if in.IsNull() {
				in.Skip()
				out.ServerConfig = nil
			} else {
				if out.ServerConfig == nil {
					out.ServerConfig = new(ServerConfig)
				}
				easyjson6615c02eDecodeGithubComModelCiApackPkgLibllamaLlamafileConfig1(in, out.ServerConfig)
			}
		case "api_config":
			if in.IsNull() {
				in.Skip()
				out.APIConfig = nil
			} else {
				if out.APIConfig == nil {
					out.APIConfig = new(APIConfig)
				}
				easyjson6615c02eDecodeGithubComModelCiApackPkgLibllamaLlamafileConfig2(in, out.APIConfig)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncodeGithubComModelCiApackPkgLibllamaLlamafileConfig(out *jwriter.Writer, in RuntimeConfig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"server_config\":"
		out.RawString(prefix[1:])
		if in.ServerConfig == nil {
			out.RawString("null")
		} else {
			easyjson6615c02eEncodeGithubComModelCiApackPkgLibllamaLlamafileConfig1(out, *in.ServerConfig)
		}
	}
	{
		const prefix string = ",\"api_config\":"
		out.RawString(prefix)
		if in.APIConfig == nil {
			out.RawString("null")
		} else {
			easyjson6615c02eEncodeGithubComModelCiApackPkgLibllamaLlamafileConfig2(out, *in.APIConfig)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RuntimeConfig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6615c02eEncodeGithubComModelCiApackPkgLibllamaLlamafileConfig(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RuntimeConfig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6615c02eEncodeGithubComModelCiApackPkgLibllamaLlamafileConfig(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RuntimeConfig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6615c02eDecodeGithubComModelCiApackPkgLibllamaLlamafileConfig(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RuntimeConfig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6615c02eDecodeGithubComModelCiApackPkgLibllamaLlamafileConfig(l, v)
}
func easyjson6615c02eDecodeGithubComModelCiApackPkgLibllamaLlamafileConfig2(in *jlexer.Lexer, out *APIConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "enabled":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Enabled = bool(in.Bool())
			}
		case "port":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Port = int(in.Int())
			}
		case "path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Path = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "theme":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Theme = string(in.String())
			}
		case "auth_enabled":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AuthEnabled = bool(in.Bool())
			}
		case "username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Password = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncodeGithubComModelCiApackPkgLibllamaLlamafileConfig2(out *jwriter.Writer, in APIConfig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"enabled\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Enabled))
	}
	{
		const prefix string = ",\"port\":"
		out.RawString(prefix)
		out.Int(int(in.Port))
	}
	{
		const prefix string = ",\"path\":"
		out.RawString(prefix)
		out.String(string(in.Path))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"theme\":"
		out.RawString(prefix)
		out.String(string(in.Theme))
	}
	{
		const prefix string = ",\"auth_enabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.AuthEnabled))
	}
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}
func easyjson6615c02eDecodeGithubComModelCiApackPkgLibllamaLlamafileConfig1(in *jlexer.Lexer, out *ServerConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "model_path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ModelPath = string(in.String())
			}
		case "host":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Host = string(in.String())
			}
		case "port":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Port = int(in.Int())
			}
		case "context_size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContextSize = int(in.Int())
			}
		case "gpu_layers":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GPULayers = int(in.Int())
			}
		case "threads":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Threads = int(in.Int())
			}
		case "start_timeout":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StartTimeout = time.Duration(in.Int64())
			}
		case "request_timeout":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RequestTimeout = time.Duration(in.Int64())
			}
		case "log_level":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LogLevel = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncodeGithubComModelCiApackPkgLibllamaLlamafileConfig1(out *jwriter.Writer, in ServerConfig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"model_path\":"
		out.RawString(prefix[1:])
		out.String(string(in.ModelPath))
	}
	{
		const prefix string = ",\"host\":"
		out.RawString(prefix)
		out.String(string(in.Host))
	}
	{
		const prefix string = ",\"port\":"
		out.RawString(prefix)
		out.Int(int(in.Port))
	}
	{
		const prefix string = ",\"context_size\":"
		out.RawString(prefix)
		out.Int(int(in.ContextSize))
	}
	{
		const prefix string = ",\"gpu_layers\":"
		out.RawString(prefix)
		out.Int(int(in.GPULayers))
	}
	{
		const prefix string = ",\"threads\":"
		out.RawString(prefix)
		out.Int(int(in.Threads))
	}
	{
		const prefix string = ",\"start_timeout\":"
		out.RawString(prefix)
		out.Int64(int64(in.StartTimeout))
	}
	{
		const prefix string = ",\"request_timeout\":"
		out.RawString(prefix)
		out.Int64(int64(in.RequestTimeout))
	}
	{
		const prefix string = ",\"log_level\":"
		out.RawString(prefix)
		out.String(string(in.LogLevel))
	}
	out.RawByte('}')
}
