// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package runtime

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	go_digest "github.com/opencontainers/go-digest"
	_v1 "github.com/opencontainers/image-spec/specs-go/v1"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBd887cf1DecodeGithubComModelCiApackInternalRuntime(in *jlexer.Lexer, out *States) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Count = int(in.Int())
			}
		case "Items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make([]State, 0, 0)
					} else {
						out.Items = []State{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v1 State
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Items = append(out.Items, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBd887cf1EncodeGithubComModelCiApackInternalRuntime(out *jwriter.Writer, in States) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Count\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Count))
	}
	{
		const prefix string = ",\"Items\":"
		out.RawString(prefix)
		if in.Items == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Items {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v States) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBd887cf1EncodeGithubComModelCiApackInternalRuntime(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v States) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBd887cf1EncodeGithubComModelCiApackInternalRuntime(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *States) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBd887cf1DecodeGithubComModelCiApackInternalRuntime(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *States) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBd887cf1DecodeGithubComModelCiApackInternalRuntime(l, v)
}
func easyjsonBd887cf1DecodeGithubComModelCiApackInternalRuntime1(in *jlexer.Lexer, out *State) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "ModelImage":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ModelImage = string(in.String())
			}
		case "CreateAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreateAt).UnmarshalJSON(data))
				}
			}
		case "Status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "Endpoints":
			if in.IsNull() {
				in.Skip()
				out.Endpoints = nil
			} else {
				in.Delim('[')
				if out.Endpoints == nil {
					if !in.IsDelim(']') {
						out.Endpoints = make([]string, 0, 4)
					} else {
						out.Endpoints = []string{}
					}
				} else {
					out.Endpoints = (out.Endpoints)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = string(in.String())
					}
					out.Endpoints = append(out.Endpoints, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "Names":
			if in.IsNull() {
				in.Skip()
				out.Names = nil
			} else {
				in.Delim('[')
				if out.Names == nil {
					if !in.IsDelim(']') {
						out.Names = make([]string, 0, 4)
					} else {
						out.Names = []string{}
					}
				} else {
					out.Names = (out.Names)[:0]
				}
				for !in.IsDelim(']') {
					var v5 string
					if in.IsNull() {
						in.Skip()
					} else {
						v5 = string(in.String())
					}
					out.Names = append(out.Names, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "mediaType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MediaType = string(in.String())
			}
		case "digest":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Digest = go_digest.Digest(in.String())
			}
		case "size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Size = int64(in.Int64())
			}
		case "urls":
			if in.IsNull() {
				in.Skip()
				out.URLs = nil
			} else {
				in.Delim('[')
				if out.URLs == nil {
					if !in.IsDelim(']') {
						out.URLs = make([]string, 0, 4)
					} else {
						out.URLs = []string{}
					}
				} else {
					out.URLs = (out.URLs)[:0]
				}
				for !in.IsDelim(']') {
					var v6 string
					if in.IsNull() {
						in.Skip()
					} else {
						v6 = string(in.String())
					}
					out.URLs = append(out.URLs, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "annotations":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Annotations = make(map[string]string)
				} else {
					out.Annotations = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v7 string
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = string(in.String())
					}
					(out.Annotations)[key] = v7
					in.WantComma()
				}
				in.Delim('}')
			}
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				out.Data = in.Bytes()
			}
		case "platform":
			if in.IsNull() {
				in.Skip()
				out.Platform = nil
			} else {
				if out.Platform == nil {
					out.Platform = new(_v1.Platform)
				}
				easyjsonBd887cf1DecodeGithubComOpencontainersImageSpecSpecsGoV1(in, out.Platform)
			}
		case "artifactType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ArtifactType = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBd887cf1EncodeGithubComModelCiApackInternalRuntime1(out *jwriter.Writer, in State) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"ModelImage\":"
		out.RawString(prefix)
		out.String(string(in.ModelImage))
	}
	{
		const prefix string = ",\"CreateAt\":"
		out.RawString(prefix)
		out.Raw((in.CreateAt).MarshalJSON())
	}
	{
		const prefix string = ",\"Status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"Endpoints\":"
		out.RawString(prefix)
		if in.Endpoints == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.Endpoints {
				if v9 > 0 {
					out.RawByte(',')
				}
				out.String(string(v10))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"Names\":"
		out.RawString(prefix)
		if in.Names == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Names {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.String(string(v12))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"mediaType\":"
		out.RawString(prefix)
		out.String(string(in.MediaType))
	}
	{
		const prefix string = ",\"digest\":"
		out.RawString(prefix)
		out.String(string(in.Digest))
	}
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.Int64(int64(in.Size))
	}
	if len(in.URLs) != 0 {
		const prefix string = ",\"urls\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v13, v14 := range in.URLs {
				if v13 > 0 {
					out.RawByte(',')
				}
				out.String(string(v14))
			}
			out.RawByte(']')
		}
	}
	if len(in.Annotations) != 0 {
		const prefix string = ",\"annotations\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v15First := true
			for v15Name, v15Value := range in.Annotations {
				if v15First {
					v15First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v15Name))
				out.RawByte(':')
				out.String(string(v15Value))
			}
			out.RawByte('}')
		}
	}
	if len(in.Data) != 0 {
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Data)
	}
	if in.Platform != nil {
		const prefix string = ",\"platform\":"
		out.RawString(prefix)
		easyjsonBd887cf1EncodeGithubComOpencontainersImageSpecSpecsGoV1(out, *in.Platform)
	}
	if in.ArtifactType != "" {
		const prefix string = ",\"artifactType\":"
		out.RawString(prefix)
		out.String(string(in.ArtifactType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v State) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBd887cf1EncodeGithubComModelCiApackInternalRuntime1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v State) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBd887cf1EncodeGithubComModelCiApackInternalRuntime1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *State) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBd887cf1DecodeGithubComModelCiApackInternalRuntime1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *State) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBd887cf1DecodeGithubComModelCiApackInternalRuntime1(l, v)
}
func easyjsonBd887cf1DecodeGithubComOpencontainersImageSpecSpecsGoV1(in *jlexer.Lexer, out *_v1.Platform) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "architecture":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Architecture = string(in.String())
			}
		case "os":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OS = string(in.String())
			}
		case "os.version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OSVersion = string(in.String())
			}
		case "os.features":
			if in.IsNull() {
				in.Skip()
				out.OSFeatures = nil
			} else {
				in.Delim('[')
				if out.OSFeatures == nil {
					if !in.IsDelim(']') {
						out.OSFeatures = make([]string, 0, 4)
					} else {
						out.OSFeatures = []string{}
					}
				} else {
					out.OSFeatures = (out.OSFeatures)[:0]
				}
				for !in.IsDelim(']') {
					var v18 string
					if in.IsNull() {
						in.Skip()
					} else {
						v18 = string(in.String())
					}
					out.OSFeatures = append(out.OSFeatures, v18)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "variant":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Variant = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBd887cf1EncodeGithubComOpencontainersImageSpecSpecsGoV1(out *jwriter.Writer, in _v1.Platform) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"architecture\":"
		out.RawString(prefix[1:])
		out.String(string(in.Architecture))
	}
	{
		const prefix string = ",\"os\":"
		out.RawString(prefix)
		out.String(string(in.OS))
	}
	if in.OSVersion != "" {
		const prefix string = ",\"os.version\":"
		out.RawString(prefix)
		out.String(string(in.OSVersion))
	}
	if len(in.OSFeatures) != 0 {
		const prefix string = ",\"os.features\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v19, v20 := range in.OSFeatures {
				if v19 > 0 {
					out.RawByte(',')
				}
				out.String(string(v20))
			}
			out.RawByte(']')
		}
	}
	if in.Variant != "" {
		const prefix string = ",\"variant\":"
		out.RawString(prefix)
		out.String(string(in.Variant))
	}
	out.RawByte('}')
}
