// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package distribution

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8c3a553aDecodeGithubComModelCiApackInternalDistribution(in *jlexer.Lexer, out *FileMetadata) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "mode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Mode = uint32(in.Uint32())
			}
		case "uid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Uid = uint32(in.Uint32())
			}
		case "gid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Gid = uint32(in.Uint32())
			}
		case "size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Size = int64(in.Int64())
			}
		case "mtime":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.ModTime).UnmarshalJSON(data))
				}
			}
		case "typeflag":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Typeflag = uint8(in.Uint8())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8c3a553aEncodeGithubComModelCiApackInternalDistribution(out *jwriter.Writer, in FileMetadata) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"mode\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Mode))
	}
	{
		const prefix string = ",\"uid\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Uid))
	}
	{
		const prefix string = ",\"gid\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Gid))
	}
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.Int64(int64(in.Size))
	}
	{
		const prefix string = ",\"mtime\":"
		out.RawString(prefix)
		out.Raw((in.ModTime).MarshalJSON())
	}
	{
		const prefix string = ",\"typeflag\":"
		out.RawString(prefix)
		out.Uint8(uint8(in.Typeflag))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FileMetadata) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8c3a553aEncodeGithubComModelCiApackInternalDistribution(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FileMetadata) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8c3a553aEncodeGithubComModelCiApackInternalDistribution(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FileMetadata) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8c3a553aDecodeGithubComModelCiApackInternalDistribution(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FileMetadata) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8c3a553aDecodeGithubComModelCiApackInternalDistribution(l, v)
}
