// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package spec

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	_v1 "github.com/modelpack/model-spec/specs-go/v1"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec(in *jlexer.Lexer, out *Package) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "workspace":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Workspace = string(in.String())
			}
		case "reference":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reference = string(in.String())
			}
		case "size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Size = int64(in.Int64())
			}
		case "digest":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Digest = string(in.String())
			}
		case "models":
			if in.IsNull() {
				in.Skip()
				out.Models = nil
			} else {
				in.Delim('[')
				if out.Models == nil {
					if !in.IsDelim(']') {
						out.Models = make([]Model, 0, 0)
					} else {
						out.Models = []Model{}
					}
				} else {
					out.Models = (out.Models)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Model
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Models = append(out.Models, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "datasets":
			if in.IsNull() {
				in.Skip()
				out.DataSets = nil
			} else {
				in.Delim('[')
				if out.DataSets == nil {
					if !in.IsDelim(']') {
						out.DataSets = make([]DataSet, 0, 0)
					} else {
						out.DataSets = []DataSet{}
					}
				} else {
					out.DataSets = (out.DataSets)[:0]
				}
				for !in.IsDelim(']') {
					var v2 DataSet
					if in.IsNull() {
						in.Skip()
					} else {
						(v2).UnmarshalEasyJSON(in)
					}
					out.DataSets = append(out.DataSets, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "codes":
			if in.IsNull() {
				in.Skip()
				out.Codes = nil
			} else {
				in.Delim('[')
				if out.Codes == nil {
					if !in.IsDelim(']') {
						out.Codes = make([]Code, 0, 1)
					} else {
						out.Codes = []Code{}
					}
				} else {
					out.Codes = (out.Codes)[:0]
				}
				for !in.IsDelim(']') {
					var v3 Code
					if in.IsNull() {
						in.Skip()
					} else {
						(v3).UnmarshalEasyJSON(in)
					}
					out.Codes = append(out.Codes, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "docs":
			if in.IsNull() {
				in.Skip()
				out.Docs = nil
			} else {
				in.Delim('[')
				if out.Docs == nil {
					if !in.IsDelim(']') {
						out.Docs = make([]Doc, 0, 1)
					} else {
						out.Docs = []Doc{}
					}
				} else {
					out.Docs = (out.Docs)[:0]
				}
				for !in.IsDelim(']') {
					var v4 Doc
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Docs = append(out.Docs, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec(out *jwriter.Writer, in Package) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Name != "" {
		const prefix string = ",\"name\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	if in.Workspace != "" {
		const prefix string = ",\"workspace\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Workspace))
	}
	if in.Reference != "" {
		const prefix string = ",\"reference\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Reference))
	}
	if in.Size != 0 {
		const prefix string = ",\"size\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Size))
	}
	if in.Digest != "" {
		const prefix string = ",\"digest\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Digest))
	}
	if len(in.Models) != 0 {
		const prefix string = ",\"models\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v5, v6 := range in.Models {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.DataSets) != 0 {
		const prefix string = ",\"datasets\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v7, v8 := range in.DataSets {
				if v7 > 0 {
					out.RawByte(',')
				}
				(v8).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.Codes) != 0 {
		const prefix string = ",\"codes\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v9, v10 := range in.Codes {
				if v9 > 0 {
					out.RawByte(',')
				}
				(v10).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.Docs) != 0 {
		const prefix string = ",\"docs\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v11, v12 := range in.Docs {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Package) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Package) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Package) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Package) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec(l, v)
}
func easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec1(in *jlexer.Lexer, out *ModelSpec) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "descriptor":
			easyjson4ca8a529DecodeGithubComModelpackModelSpecSpecsGoV1(in, &out.Descriptor)
		case "config":
			easyjson4ca8a529DecodeGithubComModelpackModelSpecSpecsGoV11(in, &out.Config)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec1(out *jwriter.Writer, in ModelSpec) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"descriptor\":"
		out.RawString(prefix[1:])
		easyjson4ca8a529EncodeGithubComModelpackModelSpecSpecsGoV1(out, in.Descriptor)
	}
	if true {
		const prefix string = ",\"config\":"
		out.RawString(prefix)
		easyjson4ca8a529EncodeGithubComModelpackModelSpecSpecsGoV11(out, in.Config)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ModelSpec) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ModelSpec) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ModelSpec) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ModelSpec) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec1(l, v)
}
func easyjson4ca8a529DecodeGithubComModelpackModelSpecSpecsGoV11(in *jlexer.Lexer, out *_v1.ModelConfig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "architecture":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Architecture = string(in.String())
			}
		case "format":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Format = string(in.String())
			}
		case "paramSize":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ParamSize = string(in.String())
			}
		case "precision":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Precision = string(in.String())
			}
		case "quantization":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Quantization = string(in.String())
			}
		case "capabilities":
			if in.IsNull() {
				in.Skip()
				out.Capabilities = nil
			} else {
				if out.Capabilities == nil {
					out.Capabilities = new(_v1.ModelCapabilities)
				}
				easyjson4ca8a529DecodeGithubComModelpackModelSpecSpecsGoV12(in, out.Capabilities)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ca8a529EncodeGithubComModelpackModelSpecSpecsGoV11(out *jwriter.Writer, in _v1.ModelConfig) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Architecture != "" {
		const prefix string = ",\"architecture\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Architecture))
	}
	if in.Format != "" {
		const prefix string = ",\"format\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Format))
	}
	if in.ParamSize != "" {
		const prefix string = ",\"paramSize\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ParamSize))
	}
	if in.Precision != "" {
		const prefix string = ",\"precision\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Precision))
	}
	if in.Quantization != "" {
		const prefix string = ",\"quantization\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Quantization))
	}
	if in.Capabilities != nil {
		const prefix string = ",\"capabilities\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson4ca8a529EncodeGithubComModelpackModelSpecSpecsGoV12(out, *in.Capabilities)
	}
	out.RawByte('}')
}
func easyjson4ca8a529DecodeGithubComModelpackModelSpecSpecsGoV12(in *jlexer.Lexer, out *_v1.ModelCapabilities) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "inputTypes":
			if in.IsNull() {
				in.Skip()
				out.InputTypes = nil
			} else {
				in.Delim('[')
				if out.InputTypes == nil {
					if !in.IsDelim(']') {
						out.InputTypes = make([]_v1.Modality, 0, 4)
					} else {
						out.InputTypes = []_v1.Modality{}
					}
				} else {
					out.InputTypes = (out.InputTypes)[:0]
				}
				for !in.IsDelim(']') {
					var v13 _v1.Modality
					if in.IsNull() {
						in.Skip()
					} else {
						v13 = _v1.Modality(in.String())
					}
					out.InputTypes = append(out.InputTypes, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "outputTypes":
			if in.IsNull() {
				in.Skip()
				out.OutputTypes = nil
			} else {
				in.Delim('[')
				if out.OutputTypes == nil {
					if !in.IsDelim(']') {
						out.OutputTypes = make([]_v1.Modality, 0, 4)
					} else {
						out.OutputTypes = []_v1.Modality{}
					}
				} else {
					out.OutputTypes = (out.OutputTypes)[:0]
				}
				for !in.IsDelim(']') {
					var v14 _v1.Modality
					if in.IsNull() {
						in.Skip()
					} else {
						v14 = _v1.Modality(in.String())
					}
					out.OutputTypes = append(out.OutputTypes, v14)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "knowledgeCutoff":
			if in.IsNull() {
				in.Skip()
				out.KnowledgeCutoff = nil
			} else {
				if out.KnowledgeCutoff == nil {
					out.KnowledgeCutoff = new(time.Time)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					if data := in.Raw(); in.Ok() {
						in.AddError((*out.KnowledgeCutoff).UnmarshalJSON(data))
					}
				}
			}
		case "reasoning":
			if in.IsNull() {
				in.Skip()
				out.Reasoning = nil
			} else {
				if out.Reasoning == nil {
					out.Reasoning = new(bool)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Reasoning = bool(in.Bool())
				}
			}
		case "toolUsage":
			if in.IsNull() {
				in.Skip()
				out.ToolUsage = nil
			} else {
				if out.ToolUsage == nil {
					out.ToolUsage = new(bool)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ToolUsage = bool(in.Bool())
				}
			}
		case "reward":
			if in.IsNull() {
				in.Skip()
				out.Reward = nil
			} else {
				if out.Reward == nil {
					out.Reward = new(bool)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Reward = bool(in.Bool())
				}
			}
		case "languages":
			if in.IsNull() {
				in.Skip()
				out.Languages = nil
			} else {
				in.Delim('[')
				if out.Languages == nil {
					if !in.IsDelim(']') {
						out.Languages = make([]string, 0, 4)
					} else {
						out.Languages = []string{}
					}
				} else {
					out.Languages = (out.Languages)[:0]
				}
				for !in.IsDelim(']') {
					var v15 string
					if in.IsNull() {
						in.Skip()
					} else {
						v15 = string(in.String())
					}
					out.Languages = append(out.Languages, v15)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ca8a529EncodeGithubComModelpackModelSpecSpecsGoV12(out *jwriter.Writer, in _v1.ModelCapabilities) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.InputTypes) != 0 {
		const prefix string = ",\"inputTypes\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v16, v17 := range in.InputTypes {
				if v16 > 0 {
					out.RawByte(',')
				}
				out.String(string(v17))
			}
			out.RawByte(']')
		}
	}
	if len(in.OutputTypes) != 0 {
		const prefix string = ",\"outputTypes\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v18, v19 := range in.OutputTypes {
				if v18 > 0 {
					out.RawByte(',')
				}
				out.String(string(v19))
			}
			out.RawByte(']')
		}
	}
	if in.KnowledgeCutoff != nil {
		const prefix string = ",\"knowledgeCutoff\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((*in.KnowledgeCutoff).MarshalJSON())
	}
	if in.Reasoning != nil {
		const prefix string = ",\"reasoning\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(*in.Reasoning))
	}
	if in.ToolUsage != nil {
		const prefix string = ",\"toolUsage\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(*in.ToolUsage))
	}
	if in.Reward != nil {
		const prefix string = ",\"reward\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(*in.Reward))
	}
	if len(in.Languages) != 0 {
		const prefix string = ",\"languages\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v20, v21 := range in.Languages {
				if v20 > 0 {
					out.RawByte(',')
				}
				out.String(string(v21))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson4ca8a529DecodeGithubComModelpackModelSpecSpecsGoV1(in *jlexer.Lexer, out *_v1.ModelDescriptor) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "createdAt":
			if in.IsNull() {
				in.Skip()
				out.CreatedAt = nil
			} else {
				if out.CreatedAt == nil {
					out.CreatedAt = new(time.Time)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					if data := in.Raw(); in.Ok() {
						in.AddError((*out.CreatedAt).UnmarshalJSON(data))
					}
				}
			}
		case "authors":
			if in.IsNull() {
				in.Skip()
				out.Authors = nil
			} else {
				in.Delim('[')
				if out.Authors == nil {
					if !in.IsDelim(']') {
						out.Authors = make([]string, 0, 4)
					} else {
						out.Authors = []string{}
					}
				} else {
					out.Authors = (out.Authors)[:0]
				}
				for !in.IsDelim(']') {
					var v22 string
					if in.IsNull() {
						in.Skip()
					} else {
						v22 = string(in.String())
					}
					out.Authors = append(out.Authors, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "family":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Family = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "docURL":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DocURL = string(in.String())
			}
		case "sourceURL":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceURL = string(in.String())
			}
		case "datasetsURL":
			if in.IsNull() {
				in.Skip()
				out.DatasetsURL = nil
			} else {
				in.Delim('[')
				if out.DatasetsURL == nil {
					if !in.IsDelim(']') {
						out.DatasetsURL = make([]string, 0, 4)
					} else {
						out.DatasetsURL = []string{}
					}
				} else {
					out.DatasetsURL = (out.DatasetsURL)[:0]
				}
				for !in.IsDelim(']') {
					var v23 string
					if in.IsNull() {
						in.Skip()
					} else {
						v23 = string(in.String())
					}
					out.DatasetsURL = append(out.DatasetsURL, v23)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = string(in.String())
			}
		case "revision":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Revision = string(in.String())
			}
		case "vendor":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Vendor = string(in.String())
			}
		case "licenses":
			if in.IsNull() {
				in.Skip()
				out.Licenses = nil
			} else {
				in.Delim('[')
				if out.Licenses == nil {
					if !in.IsDelim(']') {
						out.Licenses = make([]string, 0, 4)
					} else {
						out.Licenses = []string{}
					}
				} else {
					out.Licenses = (out.Licenses)[:0]
				}
				for !in.IsDelim(']') {
					var v24 string
					if in.IsNull() {
						in.Skip()
					} else {
						v24 = string(in.String())
					}
					out.Licenses = append(out.Licenses, v24)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ca8a529EncodeGithubComModelpackModelSpecSpecsGoV1(out *jwriter.Writer, in _v1.ModelDescriptor) {
	out.RawByte('{')
	first := true
	_ = first
	if in.CreatedAt != nil {
		const prefix string = ",\"createdAt\":"
		first = false
		out.RawString(prefix[1:])
		out.Raw((*in.CreatedAt).MarshalJSON())
	}
	if len(in.Authors) != 0 {
		const prefix string = ",\"authors\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v25, v26 := range in.Authors {
				if v25 > 0 {
					out.RawByte(',')
				}
				out.String(string(v26))
			}
			out.RawByte(']')
		}
	}
	if in.Family != "" {
		const prefix string = ",\"family\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Family))
	}
	if in.Name != "" {
		const prefix string = ",\"name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Name))
	}
	if in.DocURL != "" {
		const prefix string = ",\"docURL\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.DocURL))
	}
	if in.SourceURL != "" {
		const prefix string = ",\"sourceURL\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.SourceURL))
	}
	if len(in.DatasetsURL) != 0 {
		const prefix string = ",\"datasetsURL\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v27, v28 := range in.DatasetsURL {
				if v27 > 0 {
					out.RawByte(',')
				}
				out.String(string(v28))
			}
			out.RawByte(']')
		}
	}
	if in.Version != "" {
		const prefix string = ",\"version\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Version))
	}
	if in.Revision != "" {
		const prefix string = ",\"revision\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Revision))
	}
	if in.Vendor != "" {
		const prefix string = ",\"vendor\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Vendor))
	}
	if len(in.Licenses) != 0 {
		const prefix string = ",\"licenses\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v29, v30 := range in.Licenses {
				if v29 > 0 {
					out.RawByte(',')
				}
				out.String(string(v30))
			}
			out.RawByte(']')
		}
	}
	if in.Title != "" {
		const prefix string = ",\"title\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Title))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Description))
	}
	out.RawByte('}')
}
func easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec2(in *jlexer.Lexer, out *Model) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Path = string(in.String())
			}
		case "size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Size = int64(in.Int64())
			}
		case "license":
			if in.IsNull() {
				in.Skip()
			} else {
				out.License = string(in.String())
			}
		case "extensions":
			if m, ok := out.Extensions.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Extensions.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Extensions = in.Interface()
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec2(out *jwriter.Writer, in Model) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Name != "" {
		const prefix string = ",\"name\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	if in.Type != "" {
		const prefix string = ",\"type\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Type))
	}
	if in.Path != "" {
		const prefix string = ",\"path\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Path))
	}
	if in.Size != 0 {
		const prefix string = ",\"size\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Size))
	}
	if in.License != "" {
		const prefix string = ",\"license\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.License))
	}
	if in.Extensions != nil {
		const prefix string = ",\"extensions\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if m, ok := in.Extensions.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Extensions.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Extensions))
		}
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Model) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Model) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Model) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Model) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec2(l, v)
}
func easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec3(in *jlexer.Lexer, out *Doc) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Path = string(in.String())
			}
		case "size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Size = int64(in.Int64())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec3(out *jwriter.Writer, in Doc) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"path\":"
		out.RawString(prefix[1:])
		out.String(string(in.Path))
	}
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.Int64(int64(in.Size))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Doc) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Doc) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Doc) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Doc) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec3(l, v)
}
func easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec4(in *jlexer.Lexer, out *DataSet) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Path = string(in.String())
			}
		case "size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Size = int64(in.Int64())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "license":
			if in.IsNull() {
				in.Skip()
			} else {
				out.License = string(in.String())
			}
		case "extensions":
			if m, ok := out.Extensions.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Extensions.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Extensions = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec4(out *jwriter.Writer, in DataSet) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Name != "" {
		const prefix string = ",\"name\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	if in.Path != "" {
		const prefix string = ",\"path\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Path))
	}
	if in.Size != 0 {
		const prefix string = ",\"size\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Size))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Description))
	}
	if in.License != "" {
		const prefix string = ",\"license\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.License))
	}
	if in.Extensions != nil {
		const prefix string = ",\"extensions\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if m, ok := in.Extensions.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Extensions.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Extensions))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DataSet) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DataSet) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DataSet) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DataSet) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec4(l, v)
}
func easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec5(in *jlexer.Lexer, out *Code) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Path = string(in.String())
			}
		case "size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Size = int64(in.Int64())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "license":
			if in.IsNull() {
				in.Skip()
			} else {
				out.License = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec5(out *jwriter.Writer, in Code) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Path != "" {
		const prefix string = ",\"path\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Path))
	}
	if in.Size != 0 {
		const prefix string = ",\"size\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Size))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Description))
	}
	if in.License != "" {
		const prefix string = ",\"license\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.License))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Code) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Code) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Code) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Code) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec5(l, v)
}
func easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec6(in *jlexer.Lexer, out *Artifact) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ociVersion":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OCIVersion = string(in.String())
			}
		case "package":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Package).UnmarshalEasyJSON(in)
			}
		case "spec":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Spec).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec6(out *jwriter.Writer, in Artifact) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ociVersion\":"
		out.RawString(prefix[1:])
		out.String(string(in.OCIVersion))
	}
	if true {
		const prefix string = ",\"package\":"
		out.RawString(prefix)
		(in.Package).MarshalEasyJSON(out)
	}
	if true {
		const prefix string = ",\"spec\":"
		out.RawString(prefix)
		(in.Spec).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Artifact) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Artifact) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4ca8a529EncodeGithubComModelCiApackInternalSpec6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Artifact) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Artifact) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4ca8a529DecodeGithubComModelCiApackInternalSpec6(l, v)
}
