// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package infer

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (Config) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Config) UnmarshalJSON([]byte) error        { return nil }
func (Config) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Config) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Config *Config

func (Params) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Params) UnmarshalJSON([]byte) error        { return nil }
func (Params) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Params) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Params *Params
