// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package infer

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6615c02eDecodeGithubComModelCiApackInternalRuntimeInfer(in *jlexer.Lexer, out *Config) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "AutoRestart":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AutoRestart = bool(in.Bool())
			}
		case "MaxRetries":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxRetries = int(in.Int())
			}
		case "BasePath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BasePath = string(in.String())
			}
		case "LogPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LogPath = string(in.String())
			}
		case "PidPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PidPath = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6615c02eEncodeGithubComModelCiApackInternalRuntimeInfer(out *jwriter.Writer, in Config) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"AutoRestart\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.AutoRestart))
	}
	{
		const prefix string = ",\"MaxRetries\":"
		out.RawString(prefix)
		out.Int(int(in.MaxRetries))
	}
	{
		const prefix string = ",\"BasePath\":"
		out.RawString(prefix)
		out.String(string(in.BasePath))
	}
	{
		const prefix string = ",\"LogPath\":"
		out.RawString(prefix)
		out.String(string(in.LogPath))
	}
	{
		const prefix string = ",\"PidPath\":"
		out.RawString(prefix)
		out.String(string(in.PidPath))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Config) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6615c02eEncodeGithubComModelCiApackInternalRuntimeInfer(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Config) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6615c02eEncodeGithubComModelCiApackInternalRuntimeInfer(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Config) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6615c02eDecodeGithubComModelCiApackInternalRuntimeInfer(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Config) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6615c02eDecodeGithubComModelCiApackInternalRuntimeInfer(l, v)
}
